name: Update Price BTC

on:
  push:
#  schedule:
#    - cron: "*/2 * * * *"

jobs:
  update_price:
    name: Update Price BTC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: execute python script
        run: python /BitcoinResearch/Onchain/scripts/updateprice.py