name: Update Price BTC

on:
	workflow_dispatch:
	schedule:
		- cron: "0 */1 * * *"
jobs:
	update_price:
		name: Update Price BTC
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
			  uses: actions/checkout@v2
			- name: Run script
			  run: Onchain/scripts/updateprice.py
			
